# Timeout in minutes to keep finished repair jobs results in memory
jobs.timeout.finished.minutes=30
# Timeout in minutes after which a repair job is asked to stop. A repair does not stop, it always runs to its commit
jobs.timeout.in-progress.minutes=60
