# Timeout in minutes to keep finished scan jobs results in memory
jobs.timeout.finished.minutes=30
# Timeout in minutes after which a running scan job is asked to stop and return the results found so far
jobs.timeout.in-progress.minutes=60
